name: Build Base
on:
  workflow_dispatch:
  schedule:
  - cron: "20 19 * * *"

jobs:
  build-amd64:
    strategy:
      fail-fast: false
      matrix:
        branch: [ovn-ic-support-dual-1]
    name: Build AMD64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - uses: docker/setup-buildx-action@v2

      - name: Build
        run: |
          make base-amd64
          make base-tar-amd64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-amd64-${{ matrix.branch }}
          path: image-amd64.tar
